---
# tasks file for app
- name: Create script directory
  file:
    path: /opt/alpha
    state: directory

- name: deploy script to /opt/alpha in server node
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - { src: 'roles/appserver/files/alpha_server.py.j2', dest: '/opt/alpha/alpha_server.py' }
    - { src: 'roles/appserver/files/alpha_client.py.j2', dest: '/opt/alpha/alpha_client.py' }
    - { src: 'roles/appserver/files/alpha_report.py.j2', dest: '/opt/alpha/alpha_report.py' }

- name: deploy systemd service in server node
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - { src: 'roles/appserver/files/alpha_server.service', dest: '/etc/systemd/system/alpha_server.service' }
    - { src: 'roles/appserver/files/alpha_client.service', dest: '/etc/systemd/system/alpha_client.service' }
    - { src: 'roles/appserver/files/alpha_report.service', dest: '/etc/systemd/system/alpha_report.service' }

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes


      #- name: copy script alpha_client.py to /opt/alpha
      #  template:
      #    src: roles/app/files/alpha_client.py.j2
      #    dest: /opt/alpha/alpha_client.py
      #    mode: '0644'

